@eccomerceApi_HostAddress = https://idenitywebapiauthenitcation.fly.dev/

GET {{eccomerceApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{eccomerceApi_HostAddress}}/api/user
Authorization: Bearer CfDJ8JUAgk8d20xIiK5jj5DpYr4gKeSw70X5LLMzjX3zujut6vkFWXutBWbXVy3PxZiFTYyuGRF2KIDKE6ybyU6md23kAVFuePs5FNwGiZh-6AjckuqOjibw_AAIj8Xg_OlWg4nnHZooYzwwSvsk04PcZpZzIJII9lX2LMJdoFg9GiuODJumchRLD1ImkpDWnO1Cu8Lj8Ij5G4hgrddHfPLO35ytzy4BpdGeio46xlhtrZczR84fGqZdkHWO0iiE_2vcmfueqL_lLIQTzO_QsdwVtzG_NljnYe4XWpT_rNMIvwvXs1O3HXSH_0bjcLXVwcybcOg30q8LodMM19tZA-ZMGLPK7fbMBAhblEdr-7SrSqa_cDqkiZJOhQ9f_U5E-27Ju7gMpH0oubCqGovfBBpoBkQb4fyIAVfBMRg9vXBHhMrwDH72obMs11eWsbdmMbZf3sjHSg91rRVCHofS6DXHBzMXNYpHQ-NKbfwAraIH7zDDHLXFdlUbkCUmkLJOjdVSXEyLuUwzXP_673HmGCvfauFzTNmT8BLje5HcHKIWwZPw6dZyJvHDN2dJrWjfHte_sY8saBSUFlFWIaP5RnNPrzkMTmiFMaEzW-5EIWzFU_3JRDgH4r4CMI5ipjIJw9cYg93R5kz1i0cPLU_gcwenym1haTTJhTtClH7uLakIinjvJKAV4ypFGfxsV5W6cHrv3Q
###
